#include "a2l_generator.h"
#include <stdio.h>

void generate_a2l(const char* filename, const char* ecuName, const Variable* vars, int varCount) {
    FILE* file = fopen(filename, "w");
    if (!file) {
        printf("❌ Failed to open %s for writing\n", filename);
        return;
    }

    fprintf(file, "ASAP2_VERSION 1 71\n\n");
    fprintf(file, "/begin PROJECT %s \"Demo ECU\"\n", ecuName);
    fprintf(file, "  /begin HEADER \"Generated by sample_ecu_demo\"\n");
    fprintf(file, "  /end HEADER\n\n");
    fprintf(file, "  /begin MODULE %s_module \"Demo Module\"\n", ecuName);

    for (int i = 0; i < varCount; i++) {
        fprintf(file,
            "    /begin MEASUREMENT %s \"%s variable\" %s NO_COMPU_METHOD 1 0 %g %g\n"
            "    /end MEASUREMENT\n",
            vars[i].name,
            vars[i].name,
            vars[i].datatype,
            vars[i].minVal,
            vars[i].maxVal
        );
    }

    fprintf(file, "  /end MODULE\n");
    fprintf(file, "/end PROJECT\n");

    fclose(file);
    printf("✅ Generated A2L file: %s\n", filename);
}
