#include "a2l_generator.h"
#include <stdio.h>

void generate_a2l(const char* filename, const char* ecuName,
                  const Variable* vars, int varCount) {
    FILE* f = fopen(filename, "w");
    if (!f) { perror("open a2l"); return; }

    fprintf(f, "ASAP2_VERSION 1 71\n\n");
    fprintf(f, "/begin PROJECT %s \"Demo ECU\"\n", ecuName);
    fprintf(f, "/begin HEADER \"Generated by sample_ecu_demo\"\n");
    fprintf(f, "/end HEADER\n\n");

    fprintf(f, "  /begin MODULE %s_module \"Demo Module\"\n", ecuName);
    for (int i = 0; i < varCount; ++i) {
        fprintf(f,
          "    /begin MEASUREMENT %s \"%s variable\" %s NO_COMPU_METHOD %g %g /end MEASUREMENT\n",
          vars[i].name, vars[i].name, vars[i].datatype, vars[i].minVal, vars[i].maxVal);
    }
    fprintf(f, "  /end MODULE\n");
    fprintf(f, "/end PROJECT\n");

    fclose(f);
}
